# Input file paths
input_files:
    # Required input files
    pop_samp: ../extdata/pop_samp.csv
    founder_seqs: ../extdata/founder.fasta
    q: ../extdata/hiv_q_mat.csv
    # Optional input files related to selection ("", i.e. empty string, = not modeled)
    conserved_sites: ../extdata/founder_conserved_sites.csv
    ref_seq: ../extdata/ref.fasta
    epitope_locations: ../extdata/epitope_locations.csv

# Parameters
parameters:
    # Diversity-generating mechanisms
    mut_rate: 3.50E-05 # Mutation rate per site per generation
    recomb_rate: 1.40E-05 # Recombination rate per site per generation
    # Latent cell dynamics
    prob_act_to_lat: 0.001 # Probability of infected cell becoming latent
    prob_lat_to_act: 0.01 # Probability that a latent cell will become active
    prob_lat_prolif: 0.01 # Probability that a latent cell will proliferate (based on central memory cells)
    prob_lat_die: 0.01 # Probability that a latent cell will die
    # Parameters related to fitness
    # Conserved sites
    conserved_cost: 0.99 # Fitness cost per mutation in a conserved site
    # Replicative
    replicative_cost: 0.001 # Fitness cost per difference from reference
    # Immune
    seroconversion_time: 0 # Seroconversion time in generations; immunity considered only at this generation onward
    n_for_imm: 200 # Number new viral antigen must reach to initiate immune response against corresponding epitope
    time_to_full_potency: 90 # Number of generations for a new immune response to reach full potency
